# Generated by Django 6.1.1 on 2026-10-01 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="message",
            name="text",
        ),
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("is_muted", models.BooleanField(default=False)),
                ("muted_until", models.DateTimeField(blank=True, null=True)),
                ("is_banned", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
