# Generated by Django 6.1.1 on 2026-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_message_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="prefix_color",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
